services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fraud-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fraud-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - fraud-net

  postgres:
    image: postgres:16
    container_name: postgres_fraud_detection
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass
      POSTGRES_DB: fraud_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fraud-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraud_user -d fraud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio_fraud
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - fraud-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow_fraud_detection
    user: root
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "5001:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ./mlflow-start.sh:/mlflow-start.sh
    entrypoint: ["/bin/bash", "/mlflow-start.sh"]
    networks:
      - fraud-net

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: fraud-consumer
    depends_on:
      - kafka
      - mlflow
      - postgres
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC_IN: raw-transactions
      KAFKA_TOPIC_OUT: fraud-predictions
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_URI: models:/fraud-detector/Production
      DB_URI: postgresql://fraud_user:fraud_pass@postgres:5432/fraud_db
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ALERT_TO: ${ALERT_TO}
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    networks:
      - fraud-net
    restart: on-failure

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: fraud-producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: raw-transactions
      API_URL: https://sdacelo-real-time-fraud-detection.hf.space/current-transactions
      POLL_INTERVAL_SECONDS: 12
    networks:
      - fraud-net
    restart: on-failure

  streamlit:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: fraud-dashboard
    depends_on:
      - kafka
      - postgres
    ports:
      - "8501:8501"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: fraud-predictions
      DB_URI: postgresql://fraud_user:fraud_pass@postgres:5432/fraud_db
    networks:
      - fraud-net
    restart: on-failure

volumes:
  postgres_data:
  minio_data:

networks:
  fraud-net: